Repository joinfaces/joinfaces, pull requests merged in 2018-10, with the labels that each got.

#550 Update to MyFaces 2.3.2
  joinfaces-dependencies/pom.xml
Labels: enhancement

#551 Update to Lombok 1.18.2
  joinfaces-dependencies/pom.xml
Labels: enhancement

#552 Update to Primefaces Extensions 6.2.9
  joinfaces-dependencies/pom.xml
Labels: enhancement

#553 Update to Butterfaces 3.0.6
  joinfaces-dependencies/pom.xml
Labels: enhancement

#554 Update AdminFaces to 1.0.0-RC19
  joinfaces-dependencies/pom.xml
Labels: enhancement

#555 configure AdminFaces using Spring Boot application.yml or application.properties
  README.md
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminConfigWrapper.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminfacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminfacesProperties.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/adminfaces/AdminfacesAutoConfigurationTest.java
  joinfaces-autoconfigure/src/test/resources/admin-config.properties
Labels: enhancement

#556 Update to Spring Boot 2.0.6
  joinfaces-autoconfigure/pom.xml
  joinfaces-dependencies/pom.xml
Labels: enhancement

#557 Update Spring Boot to 2.1.0.RC1
  joinfaces-dependencies/pom.xml
Labels: enhancement

#560 Update Checkstyle to 8.13
  joinfaces-dependencies/pom.xml
Labels: task

#561 Remove broken versioneye link. Add icefaces namespace example
  README.md
Labels: documentation

#562 Add IceFaces link
  README.md
Labels: documentation

#567 Update to Spring Boot 2.1.0.RELEASE
  joinfaces-dependencies/pom.xml
Labels: enhancement
