Repository joinfaces/joinfaces, pull requests merged in 2018-04, with the labels that each got.

#438 remove unused rewrite test properties
  joinfaces-autoconfigure/src/test/resources/application-propertyTest.yml
Labels: task

#439 fix minor checkstyle error
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/RewriteAutoConfiguration.java
Labels: task

#440 fix minor findbugs error
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/ApplicationContextProvider.java
Labels: task

#441 rewrite lookup spring beans fix
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/RewriteAutoConfiguration.java
Labels: enhancement

#442 preparing 3.1.0 release
  joinfaces-autoconfigure/pom.xml
  joinfaces-dependencies/pom.xml
  joinfaces-parent/pom.xml
  joinfaces-starters/angularfaces-spring-boot-starter/pom.xml
  joinfaces-starters/bootsfaces-spring-boot-starter/pom.xml
  joinfaces-starters/butterfaces-spring-boot-starter/pom.xml
  joinfaces-starters/jetty-spring-boot-starter/pom.xml
  joinfaces-starters/jsf-spring-boot-starter/pom.xml
  joinfaces-starters/mojarra-spring-boot-starter/pom.xml
  joinfaces-starters/myfaces-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces1-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces3-spring-boot-starter/pom.xml
  joinfaces-starters/pom.xml
  joinfaces-starters/primefaces-spring-boot-starter/pom.xml
  joinfaces-starters/rewrite-spring-boot-starter/pom.xml
  joinfaces-starters/richfaces-spring-boot-starter/pom.xml
  joinfaces-starters/tomcat-spring-boot-starter/pom.xml
  joinfaces-starters/undertow-spring-boot-starter/pom.xml
  joinfaces-starters/weld-spring-boot-starter/pom.xml
  joinfaces-test/pom.xml
  pom.xml
  spring-security-jsf-taglib/pom.xml
  test-projects/jetty-mojarra/pom.xml
  test-projects/jetty-myfaces/pom.xml
  test-projects/pom.xml
  test-projects/tomcat-mojarra/pom.xml
  test-projects/tomcat-myfaces/pom.xml
  test-projects/undertow-mojarra/pom.xml
  test-projects/undertow-myfaces/pom.xml
Labels: task

#443 Do not deploy test-projects
  test-projects/pom.xml
Labels: task

#444 Minor Readme.md fix
  README.md
Labels: documentation

#445 document missing joinfaces autoconfigure packages
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/package-info.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/package-info.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/viewscope/package-info.java
Labels: documentation

#450 Test codecov.io
  .travis.yml
  README.md
Labels: task

#449 Java 9 compatibility
  .travis.yml
  joinfaces-autoconfigure/pom.xml
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/JsfClassFactory.java
  joinfaces-dependencies/pom.xml
  test-projects/pom.xml
Labels: feature

#451 upgrade mojarra to 2.3.4
  joinfaces-dependencies/pom.xml
Labels: enhancement

#453 Update README.md
  README.md
Labels: documentation

#458 avoid ReflectionException with war packaging
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/JsfClassFactory.java
Labels: enhancement

#459 upgrade mojarra to 2.3.3.99
  joinfaces-dependencies/pom.xml
Labels: enhancement

#461 upgrade primefaces-extensions to 6.2.4
  joinfaces-dependencies/pom.xml
Labels: enhancement

#462 upgrade joinfaces snapshot to 3.2.0-SNAPSHOT
  joinfaces-autoconfigure/pom.xml
  joinfaces-dependencies/pom.xml
  joinfaces-parent/pom.xml
  joinfaces-starters/adminfaces-spring-boot-starter/pom.xml
  joinfaces-starters/angularfaces-spring-boot-starter/pom.xml
  joinfaces-starters/bootsfaces-spring-boot-starter/pom.xml
  joinfaces-starters/butterfaces-spring-boot-starter/pom.xml
  joinfaces-starters/jetty-spring-boot-starter/pom.xml
  joinfaces-starters/jsf-spring-boot-starter/pom.xml
  joinfaces-starters/mojarra-spring-boot-starter/pom.xml
  joinfaces-starters/myfaces-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces1-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces3-spring-boot-starter/pom.xml
  joinfaces-starters/pom.xml
  joinfaces-starters/primefaces-spring-boot-starter/pom.xml
  joinfaces-starters/rewrite-spring-boot-starter/pom.xml
  joinfaces-starters/richfaces-spring-boot-starter/pom.xml
  joinfaces-starters/tomcat-spring-boot-starter/pom.xml
  joinfaces-starters/undertow-spring-boot-starter/pom.xml
  joinfaces-starters/weld-spring-boot-starter/pom.xml
  joinfaces-test/pom.xml
  pom.xml
  spring-security-jsf-taglib/pom.xml
  test-projects/jetty-mojarra/pom.xml
  test-projects/jetty-myfaces/pom.xml
  test-projects/pom.xml
  test-projects/tomcat-mojarra/pom.xml
  test-projects/tomcat-myfaces/pom.xml
  test-projects/undertow-mojarra/pom.xml
  test-projects/undertow-myfaces/pom.xml
Labels: task

#464 upgrade mojarra to 2.3.4 again
  joinfaces-dependencies/pom.xml
Labels: enhancement

#465 upgrade maven to 3.5.3
  .mvn/wrapper/maven-wrapper.properties
Labels: enhancement

#466 upgrade nexus-staging-maven-plugin to 1.6.8
  pom.xml
Labels: task

#467 upgrade maven-javadoc-plugin to 3.0.0
  pom.xml
Labels: enhancement

#468 upgrade adminfaces to 1.0.0-RC14
  joinfaces-dependencies/pom.xml
Labels: enhancement

#469 simplify Richfaces Configuration
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/richfaces/RichfacesAutoConfiguration.java
Labels: enhancement
