Repository joinfaces/joinfaces, pull requests merged in 2018-06, with the labels that each got.

#490 Proposal: Remove strict coverage limits
  joinfaces-autoconfigure/pom.xml
  joinfaces-dependencies/pom.xml
  joinfaces-test/pom.xml
Labels: task

#501 Improve Rewrite including SpringBootExpressionLanguageProvider
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/SpringBootExpressionLanguageProvider.java
  joinfaces-autoconfigure/src/main/resources/META-INF/services/org.ocpsoft.rewrite.el.spi.ExpressionLanguageProvider
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/rewrite/SpringBootExpressionLanguageProviderTest.java
Labels: enhancement

#504 add cdi-api dependency to adminfaces-spring-boot-starter
  joinfaces-starters/adminfaces-spring-boot-starter/pom.xml
Labels: bug
