Repository joinfaces/joinfaces, pull requests merged in 2018-02, with the labels that each got.

#386 Remove redundant code
  .idea/checkstyle-idea.xml
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/configuration/InitParameterServletContextConfigurer.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/ViewScope.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProvider.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/primefaces/PrimefacesFileUploadServletContextInitializer.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/richfaces/RichfacesSpringBootAutoConfiguration.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/configuration/InitParameterServletContextConfigurerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/ViewScopeIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/jetty/JettySpringBootAutoConfigurationIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/jetty/JsfJettyServerCustomizerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/mojarra/MojarraServletContextInitializerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProviderTests.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/MyfacesServletContextInitializerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/omnifaces/OmnifacesServletContextInitializerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/primefaces/CommonsPrimefacesFileUploadServletContextInitializerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/primefaces/PrimefacesFileUploadServletContextInitializerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/tomcat/ContextMock.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListenerIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/tomcat/MockWebResourceRoot.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/tomcat/TomcatSpringBootAutoConfigurationIT.java
  joinfaces-test/src/main/java/org/joinfaces/test/mock/FacesContextMocker.java
  joinfaces-test/src/main/java/org/joinfaces/test/mock/MockFaceletContext.java
  joinfaces-test/src/main/java/org/joinfaces/test/mock/MockFaceletHandler.java
  joinfaces-test/src/test/java/org/joinfaces/test/mock/MockFaceletContextTest.java
  spring-security-jsf-taglib/src/main/java/org/joinfaces/security/AuthorizeFaceletsTagHandler.java
Labels: enhancement

#384 joinfaces dependencies
  joinfaces-dependencies/pom.xml
  joinfaces-dependencies/src/checkconfig/findbugs/findbugs-exclude.xml
  joinfaces-parent/pom.xml
  pom.xml
Labels: feature

#388 link README to joinfaces-dependencies versioneye project
  README.md
Labels: task

#393 Support destruction callbacks for view-scoped beans
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/JsfScopeAnnotationsAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/ViewScope.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/viewscope/DestructionCallbackWrapper.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/viewscope/SessionHelper.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/viewscope/ViewScope.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/integration/viewscope/ViewScopeAutoConfiguration.java
  joinfaces-autoconfigure/src/main/resources/META-INF/spring.factories
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/JsfCdiToSpringApplicationBeanFactoryPostProcessorIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/ViewScopeAutoConfigurationTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/ViewScopeIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/viewscope/DestructionCallbackWrapperTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/viewscope/SessionHelperTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/viewscope/ViewScopeAutoConfigurationIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/viewscope/ViewScopeDestructionCallbackIT.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/viewscope/ViewScopeErrorsTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/integration/viewscope/ViewScopeTest.java
  joinfaces-dependencies/pom.xml
  joinfaces-parent/pom.xml
Labels: enhancement
