Repository joinfaces/joinfaces, pull requests merged in 2018-11, with the labels that each got.

#570 deploy release with travis
  .gitignore
  .travis.yml
  gradle.properties
  secring.gpg.enc
Labels: task

#571 create absolute secring.gpg to fix signing error at travis build
  .travis.yml
  gradle.properties
Labels: task

#572 automate close and release nexus repository after publish
  .travis.yml
  build.gradle
Labels: task

#574 Fix nexus publishing on travis
  .travis.yml
  build.gradle
Labels: enhancement

#576 Enhance jar manifests
  build.gradle
  joinfaces-autoconfigure/build.gradle
  joinfaces-starters/adminfaces-spring-boot-starter/build.gradle
  joinfaces-starters/angularfaces-spring-boot-starter/build.gradle
  joinfaces-starters/bootsfaces-spring-boot-starter/build.gradle
  joinfaces-starters/butterfaces-spring-boot-starter/build.gradle
  joinfaces-starters/icefaces-spring-boot-starter/build.gradle
  joinfaces-starters/jetty-spring-boot-starter/build.gradle
  joinfaces-starters/jsf-spring-boot-starter/build.gradle
  joinfaces-starters/mojarra-spring-boot-starter/build.gradle
  joinfaces-starters/myfaces-spring-boot-starter/build.gradle
  joinfaces-starters/omnifaces1-spring-boot-starter/build.gradle
  joinfaces-starters/omnifaces3-spring-boot-starter/build.gradle
  joinfaces-starters/primefaces-spring-boot-starter/build.gradle
  joinfaces-starters/rewrite-spring-boot-starter/build.gradle
  joinfaces-starters/richfaces-spring-boot-starter/build.gradle
  joinfaces-starters/tomcat-spring-boot-starter/build.gradle
  joinfaces-starters/undertow-spring-boot-starter/build.gradle
  joinfaces-starters/weld-spring-boot-starter/build.gradle
  joinfaces-test/build.gradle
  spring-security-jsf-taglib/build.gradle
  test-projects/jetty-mojarra/build.gradle
  test-projects/jetty-myfaces/build.gradle
  test-projects/tomcat-mojarra/build.gradle
  test-projects/tomcat-myfaces/build.gradle
  test-projects/undertow-mojarra/build.gradle
  test-projects/undertow-myfaces/build.gradle
Labels: enhancement

#565 Use classgraph instead of reflections
  .idea/checkstyle-idea.xml
  build.gradle
  joinfaces-autoconfigure/build.gradle
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/mojarra/MojarraAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/mojarra/MojarraInitializerRegistrationBean.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProvider.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyFacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyFacesInitializerRegistrationBean.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/JsfClassFactory.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/ServletContainerInitializerRegistrationBean.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListener.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/mojarra/JsfClassFactoryTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/mojarra/MojarraInitializerRegistrationBeanTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProviderTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/JsfClassFactoryTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/MyFacesInitializerRegistrationBeanTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/servlet/initializer/ServletContainerInitializerRegistrationBeanTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/servlet/initializer/TypesHandledTest.java
  joinfaces-tools/build.gradle
  joinfaces-tools/joinfaces-gradle-plugin/build.gradle
  joinfaces-tools/joinfaces-gradle-plugin/src/main/java/org/joinfaces/gradle/ClasspathScan.java
  joinfaces-tools/joinfaces-gradle-plugin/src/main/java/org/joinfaces/gradle/ClasspathScanPlugin.java
  joinfaces-tools/joinfaces-gradle-plugin/src/main/java/org/joinfaces/gradle/JoinfacesPlugin.java
  joinfaces-tools/joinfaces-gradle-plugin/src/test/java/org/joinfaces/gradle/ClasspathScanPluginTest.java
  joinfaces-tools/joinfaces-gradle-plugin/src/test/java/org/joinfaces/gradle/JoinfacesPluginIT.java
  joinfaces-tools/joinfaces-gradle-plugin/src/test/java/org/joinfaces/gradle/JoinfacesPluginTest.java
  joinfaces-tools/joinfaces-maven-plugin/build.gradle
  joinfaces-tools/joinfaces-maven-plugin/src/main/java/org/joinfaces/maven/ClasspathScanMojo.java
  joinfaces-tools/joinfaces-maven-plugin/src/test/java/org/joinfaces/maven/ClasspathScanMojoTest.java
  joinfaces-tools/joinfaces-scan-tools/build.gradle
  joinfaces-tools/joinfaces-scan-tools/src/main/java/org/joinfaces/tools/ClasspathScanner.java
  joinfaces-tools/joinfaces-scan-tools/src/test/java/org/joinfaces/tools/ClasspathScannerTest.java
  settings.gradle
  test-projects/build.gradle
Labels: enhancement

#577 remove jboss-annotations-api_1.2_spec dependency from undertow
  joinfaces-starters/undertow-spring-boot-starter/build.gradle
Labels: enhancement

#578 update mojarra to 2.3.8
  build.gradle
Labels: enhancement

#579 update primefaces extensions to 6.2.10
  build.gradle
Labels: enhancement

#581 update gradle-lint to 10.3.1
  build.gradle
Labels: enhancement

#582 update lombok-plugin and maven-plugin to 2.9.1
  build.gradle
Labels: enhancement

#583 adding jboss-logging to weld-spring-boot-starter
  build.gradle
  joinfaces-starters/weld-spring-boot-starter/build.gradle
Labels: enhancement

#584 AdminFaces: add error page to AccessLocalException
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminfacesAutoConfiguration.java
Labels: enhancement

#589 update AdminFaces to 1.0.0-RC20
  build.gradle
Labels: enhancement

#586 Asciidoc reference documentation
  .travis.yml
  build.gradle
  buildSrc/.gitignore
  buildSrc/build.gradle
  buildSrc/src/main/java/org/joinfaces/build/UploadDocumentation.java
  src/docs/asciidoc/index.adoc
Labels: documentation, enhancement, help wanted, ideal-for-contribution

#591 Fail build for invalid pom's
  build.gradle
  joinfaces-tools/joinfaces-gradle-plugin/build.gradle
  joinfaces-tools/joinfaces-maven-plugin/build.gradle
  joinfaces-tools/joinfaces-scan-tools/build.gradle
Labels: bug

#592 Update to Spring Boot 2.1.1.RELEASE
  build.gradle
  joinfaces-tools/joinfaces-gradle-plugin/build.gradle
Labels: enhancement

#593 adding missing package-info.java class
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/icefaces/package-info.java
  joinfaces-tools/joinfaces-maven-plugin/src/main/java/org/joinfaces/maven/package-info.java
  joinfaces-tools/joinfaces-scan-tools/src/main/java/org/joinfaces/tools/package-info.java
Labels: task

#594 Automatically calculate a version number when possible
  .travis.yml
  build.gradle
Labels: enhancement
