Repository joinfaces/joinfaces, pull requests merged in 2018-03, with the labels that each got.

#389 Upgrade Spring Boot to 2.0.0.RELEASE
  joinfaces-dependencies/pom.xml
Labels: feature

#400 Reuse tomcat and lombok from spring boot dependencies
  joinfaces-dependencies/pom.xml
Labels: task

#401 upgrade lombok-maven-plugin to 1.16.20.0
  joinfaces-dependencies/pom.xml
Labels: enhancement

#402 upgrade myfaces to 2.3.0
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyFacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyFacesInitializerRegistrationBean.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyfacesProperties.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/JsfClassFactoryTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/MyFacesInitializerRegistrationBeanTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/MyfacesPropertiesDeprecatedIT.java
  joinfaces-autoconfigure/src/test/resources/application-propertyTest.yml
  joinfaces-dependencies/pom.xml
Labels: feature

#403 upgrade jboss-jsp-api_2.3_spec to 1.0.3.Final
  joinfaces-dependencies/pom.xml
Labels: enhancement

#404 upgrade duplicate-finder-maven-plugin to 1.3.0
  joinfaces-dependencies/pom.xml
Labels: enhancement

#406 Upgrade maven-pmd-plugin to 3.9.0
  joinfaces-dependencies/pom.xml
  joinfaces-parent/src/checkconfig/pmd/pmd-ruleset.xml
Labels: enhancement

#407 upgrade primefaces to 6.2
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/primefaces/Primefaces6_2Properties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/primefaces/PrimefacesAutoConfiguration.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/primefaces/PrimefacesPropertiesIT.java
  joinfaces-autoconfigure/src/test/resources/application-propertyTest.yml
  joinfaces-dependencies/pom.xml
  joinfaces-starters/primefaces-spring-boot-starter/pom.xml
Labels: feature

#408 preparing 3.0.0 release
  joinfaces-autoconfigure/pom.xml
  joinfaces-dependencies/pom.xml
  joinfaces-parent/pom.xml
  joinfaces-starters/angularfaces-spring-boot-starter/pom.xml
  joinfaces-starters/bootsfaces-spring-boot-starter/pom.xml
  joinfaces-starters/butterfaces-spring-boot-starter/pom.xml
  joinfaces-starters/jetty-spring-boot-starter/pom.xml
  joinfaces-starters/jsf-spring-boot-starter/pom.xml
  joinfaces-starters/mojarra-spring-boot-starter/pom.xml
  joinfaces-starters/myfaces-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces-spring-boot-starter/pom.xml
  joinfaces-starters/pom.xml
  joinfaces-starters/primefaces-spring-boot-starter/pom.xml
  joinfaces-starters/richfaces-spring-boot-starter/pom.xml
  joinfaces-starters/tomcat-spring-boot-starter/pom.xml
  joinfaces-starters/undertow-spring-boot-starter/pom.xml
  joinfaces-test/pom.xml
  pom.xml
  spring-security-jsf-taglib/pom.xml
Labels: task

#409 move project information from dependencies to parent
  joinfaces-dependencies/pom.xml
  joinfaces-parent/pom.xml
Labels: task

#411 inherit spring-boot-starter-parent
  joinfaces-dependencies/pom.xml
  joinfaces-parent/pom.xml
Labels: enhancement

#415 enable tomcat to read BOOT-INF/classes/META-INF/resources
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListener.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListenerIT.java
Labels: enhancement

#416 remove unnecessary comment
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListener.java
Labels: task

#417 fix gradleJarPackaging with tomcat implementation
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListener.java
Labels: task

#419 Manually register the FacesServlet
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/FacesServletAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/FacesServletProperties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/JavaxFacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  joinfaces-autoconfigure/src/main/resources/META-INF/spring.factories
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/javaxfaces/FacesServletAutoConfigurationTest.java
Labels: enhancement

#391 Weld Spring Boot Starter
  joinfaces-autoconfigure/pom.xml
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/omnifaces/OmnifacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/omnifaces/OmnifacesInitializerRegistrationBean.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/omnifaces/OmnifacesProperties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/ServletContainerInitializerRegistrationBean.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/weld/WeldSpringBootAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/weld/package-info.java
  joinfaces-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  joinfaces-autoconfigure/src/main/resources/META-INF/spring.factories
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/omnifaces/Omnifaces2AutoConfigurationTest.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/weld/WeldSpringBootAutoConfigurationTest.java
  joinfaces-dependencies/pom.xml
  joinfaces-starters/jsf-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces1-spring-boot-starter/nbactions.xml
  joinfaces-starters/omnifaces1-spring-boot-starter/pom.xml
  joinfaces-starters/omnifaces3-spring-boot-starter/pom.xml
  joinfaces-starters/pom.xml
  joinfaces-starters/weld-spring-boot-starter/pom.xml
Labels: feature

#423 update README and CONTRIBUTING after weld and omnifaces feature
  CONTRIBUTING.md
  README.md
Labels: documentation

#424 Remove extra classloader for jetty
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/jetty/JettyAutoConfiguration.java
Labels: enhancement

#426 Manually register Mojarras ConfigureListener for an embedded undertow.
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/undertow/UndertowAutoConfiguration.java
Labels: enhancement

#429 Improve build for starter projects
  joinfaces-starters/pom.xml
Labels: enhancement

#435 upgrade primefaces-extensions to 6.2.3
  joinfaces-dependencies/pom.xml
Labels: enhancement

#437 Use @SuppressFBWarnings instead of xml files
  joinfaces-autoconfigure/pom.xml
  joinfaces-autoconfigure/src/checkconfig/findbugs/findbugs-exclude.xml
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProvider.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProviderTests.java
  joinfaces-autoconfigure/src/test/java/org/joinfaces/autoconfigure/tomcat/JsfTomcatApplicationListenerIT.java
  joinfaces-dependencies/pom.xml
  joinfaces-dependencies/src/checkconfig/findbugs/findbugs-exclude.xml
  joinfaces-parent/src/checkconfig/findbugs/findbugs-exclude.xml
Labels: enhancement
