Repository joinfaces/joinfaces, pull requests merged in 2018-12, with the labels that each got.

#595 Make loading the prepared scan result a bit more robust
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProvider.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/ServletContainerInitializerRegistrationBean.java
Labels: bug

#597 Fix loading of prepared myfaces scan result
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/JoinFacesAnnotationProvider.java
Labels: bug

#598 Automatic documentation for all properties
  .gitignore
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/org/joinfaces/build/BomDocumentation.java
  buildSrc/src/main/java/org/joinfaces/build/PropertyDocumentation.java
  joinfaces-autoconfigure/build.gradle
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/JavaxFaces2_0Properties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/JavaxFaces2_1Properties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/JavaxFaces2_2Properties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/javaxfaces/JavaxFaces2_3Properties.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/omnifaces/OmnifacesProperties.java
  joinfaces-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/docs/asciidoc/asciidoctor.css
  src/docs/asciidoc/index.adoc
Labels: documentation, enhancement

#599 update ClassGraph to 4.6.3
  build.gradle
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/ServletContainerInitializerRegistrationBean.java
Labels: enhancement

#602 Update README according to new joinfaces namespace
  README.md
Labels: documentation

#605 Update to ClassGraph 4.6.6
  build.gradle
Labels: enhancement

#603 Document what JoinFaces does for different libraries
  src/docs/asciidoc/_build-tools.adoc
  src/docs/asciidoc/_features.adoc
  src/docs/asciidoc/_getting-started.adoc
  src/docs/asciidoc/_how-to-faq.adoc
  src/docs/asciidoc/index.adoc
Labels: documentation

#606 Don't exclude and then re-include jboss-logging
  build.gradle
  joinfaces-starters/weld-spring-boot-starter/build.gradle
Labels: enhancement

#608 Improve Spring Security JSF Facelet Tags documentation
  src/docs/asciidoc/_features.adoc
Labels: documentation

#609 Publish the Gradle plugin to plugins.gradle.org
  .travis.yml
Labels: enhancement

#611 adding bagdes of api and reference current documentation
  README.md
Labels: documentation

#610 Add security-spring-boot-starter
  joinfaces-security-taglib/build.gradle
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AbstractFaceletsAuthorizeTag.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AnonymousFaceletsTag.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AnonymousFaceletsTagHandler.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AuthenticatedFaceletsTag.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AuthenticatedFaceletsTagHandler.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AuthorizeFaceletsTag.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/AuthorizeFaceletsTagHandler.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/FaceletsTagUtils.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/FullyAuthenticatedFaceletsTag.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/FullyAuthenticatedFaceletsTagHandler.java
  joinfaces-security-taglib/src/main/java/org/joinfaces/security/package-info.java
  joinfaces-security-taglib/src/main/resources/META-INF/springsecurity.taglib.xml
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AnonymousFaceletsTagHandlerIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AnonymousFaceletsTagIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AuthenticatedFaceletsTagHandlerIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AuthenticatedFaceletsTagIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AuthenticationFactory.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AuthorizeFaceletsTagHandlerIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/AuthorizeFaceletsTagIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/FaceletsTagUtilsIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/FullyAuthenticatedFaceletsTagHandlerIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/FullyAuthenticatedFaceletsTagIT.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/Roles.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/SecurityConfiguration.java
  joinfaces-security-taglib/src/test/java/org/joinfaces/security/SpringSecurityMock.java
  joinfaces-security-taglib/src/test/resources/logback.xml
  joinfaces-starters/jsf-spring-boot-starter/build.gradle
  joinfaces-starters/security-spring-boot-starter/build.gradle
  settings.gradle
  src/docs/asciidoc/_features.adoc
Labels: feature

#617 Update to CDI API 2.0.SP1
  build.gradle
Labels: enhancement

#620 Update to ClassGraph 4.6.10
  build.gradle
Labels: dependency-upgrade
