Repository joinfaces/joinfaces, pull requests merged in 2019-05, with the labels that each got.

#661 Update to OmniFaces 3.3
  joinfaces-starters/omnifaces3-spring-boot-starter/build.gradle
Labels: dependency-upgrade

#663 Update to AdminFaces 1.0.0
  build.gradle
Labels: dependency-upgrade

#664 Upgrade butterfaces to 3.1.1
  build.gradle
Labels: dependency-upgrade

#662 Update to ClassGraph 4.8.29
  build.gradle
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/initializer/ServletContainerInitializerRegistrationBean.java
  joinfaces-tools/joinfaces-scan-tools/src/main/java/org/joinfaces/tools/ServletContainerInitializerHandler.java
Labels: dependency-upgrade

#665 Update to Weld 3.0.6.Final
  build.gradle
Labels: dependency-upgrade

#666 Update to Spring Boot 2.1.4.RELEASE
  buildSrc/build.gradle
Labels: dependency-upgrade

#667 Update to Weld 3.1.1.Final
  build.gradle
Labels: dependency-upgrade

#668 Update to Gradle 5.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependency-upgrade

#655 Test Java 12 on Travis
  .travis.yml
  README.md
  build.gradle
Labels: enhancement

#670 Update to Gradle Lint Plugin 11.5.0
  build.gradle
Labels: dependency-upgrade

#671 Update to Gradle CPD Plugin 1.3
  build.gradle
Labels: dependency-upgrade

#669 Update to SpotBugs Gradle Plugin 1.7.1
  build.gradle
Labels: dependency-upgrade

#679 Add initial Tobago support
  build.gradle
  joinfaces-autoconfigure/build.gradle
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/tobago/TobagoAutoConfiguration.java
  joinfaces-autoconfigure/src/main/resources/META-INF/spring.factories
  joinfaces-starters/tobago-spring-boot-starter/build.gradle
  settings.gradle
Labels: feature

#678 Update to Spring Boot 2.2.0.M3
  buildSrc/build.gradle
  joinfaces-test/src/main/java/org/joinfaces/test/mock/MockMethodMetadata.java
  joinfaces-test/src/test/java/org/joinfaces/test/mock/MockMethodMetadataTest.java
Labels: dependency-upgrade

#680 Update to PrimeFaces Extensions 7.0.1
  build.gradle
Labels: dependency-upgrade

#681 Update to SpotBugs Gradle Plugin 2.0.0
  build.gradle
Labels: dependency-upgrade

#685 Update to Spring Boot 2.1.5
  buildSrc/build.gradle
Labels: dependency-upgrade

#684 Improve registration of web-fragment.xml listeners
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/adminfaces/AdminfacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/myfaces/MyFacesAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/rewrite/RewriteAutoConfiguration.java
  joinfaces-autoconfigure/src/main/java/org/joinfaces/autoconfigure/servlet/WebFragmentRegistrationBean.java
  test-projects/src/main/resources/application.properties
  test-projects/src/test/resources/application.properties
Labels: bug

#682 Update the Gradle Plugin to use Gradle 5 features
  joinfaces-tools/joinfaces-gradle-plugin/src/main/java/org/joinfaces/gradle/ClasspathScan.java
  joinfaces-tools/joinfaces-gradle-plugin/src/main/java/org/joinfaces/gradle/ClasspathScanPlugin.java
  joinfaces-tools/joinfaces-gradle-plugin/src/test/java/org/joinfaces/gradle/JoinfacesPluginIT.java
Labels: enhancement

#672 Generate an aggregated coverage report
  .travis.yml
  build.gradle
Labels: enhancement
